services:
  lumgr:
    build: .
    # image: ghcr.io/hnrobert/lumgr:latest
    container_name: lumgr
    ports:
      - "14392:14392"
    environment:
      - LUMGR_LISTEN=:14392
      - LUMGR_HOST_ROOT=/host
    user: "0:0"
    volumes:
      - /etc/passwd:/host/etc/passwd
      - /etc/shadow:/host/etc/shadow
      - /etc/group:/host/etc/group
      - /home:/host/home
    restart: unless-stopped
