services:
  lumgr:
    # build: .
    image: ghcr.io/hnrobert/lumgr:latest
    container_name: lumgr
    ports:
      - "14392:14392"
    environment:
      - LUMGR_LISTEN=:14392
      - LUMGR_JWT_SECRET=your-secret-key-here # Optional: Set custom JWT secret
    volumes:
      - ./lumgr_data:/lumgr_data # Config & invite storage
      - /home:/home # User home directories
      - /etc/passwd:/etc/passwd # User database
      - /etc/shadow:/etc/shadow # Password hashes
      - /etc/group:/etc/group # Group database
      - /etc/localtime:/etc/localtime:ro # Timezone info
      - /etc/shells:/etc/shells:ro # Available shells
      - /etc/os-release:/etc/os-release:ro # OS info
      - /etc/hostname:/etc/hostname:ro # Hostname
    restart: always
