services:
  lumgr:
    build: .
    # image: ghcr.io/hnrobert/lumgr:latest
    container_name: lumgr
    ports:
      - "14392:14392"
    environment:
      - LUMGR_LISTEN=:14392
      # Optional: make bind-mounted ./lumgr_data writeable for the host user
      # who started the container.
      - LUMGR_DATA_UID=$(id -u)
    volumes:
      - ./lumgr_data:/var/lib/lumgr
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - /home:/home
    restart: always
